echo height_base_add.out.txt && diff height_base_add.out.txt  test_other/height_base_add.out.txt
echo height_base_fv_add.out.txt && diff height_base_fv_add.out.txt  test_other/height_base_fv_add.out.txt
echo height_allcov_add.out.txt && diff height_allcov_add.out.txt  test_other/height_allcov_add.out.txt
echo height_allcov_fv_add.out.txt && diff height_allcov_fv_add.out.txt  test_other/height_allcov_fv_add.out.txt
echo height_int1_add.out.txt && diff height_int1_add.out.txt  test_other/height_int1_add.out.txt
echo height_int1_fv_add.out.txt && diff height_int1_fv_add.out.txt  test_other/height_int1_fv_add.out.txt
echo height_robust_add.out.txt && diff height_robust_add.out.txt  test_other/height_robust_add.out.txt
echo height_robust_fv_add.out.txt && diff height_robust_fv_add.out.txt  test_other/height_robust_fv_add.out.txt
echo height_robust_int1_add.out.txt && diff height_robust_int1_add.out.txt  test_other/height_robust_int1_add.out.txt
echo height_robust_int1_fv_add.out.txt && diff height_robust_int1_fv_add.out.txt  test_other/height_robust_int1_fv_add.out.txt
echo height_ngp2_add.out.txt && diff height_ngp2_add.out.txt  test_other/height_ngp2_add.out.txt
echo height_ngp2_fv_add.out.txt && diff height_ngp2_fv_add.out.txt  test_other/height_ngp2_fv_add.out.txt
echo height_ngp2_domin.out.txt && diff height_ngp2_domin.out.txt  test_other/height_ngp2_domin.out.txt
echo height_ngp2_fv_domin.out.txt && diff height_ngp2_fv_domin.out.txt  test_other/height_ngp2_fv_domin.out.txt
echo height_ngp2_over_domin.out.txt && diff height_ngp2_over_domin.out.txt  test_other/height_ngp2_over_domin.out.txt
echo height_ngp2_fv_over_domin.out.txt && diff height_ngp2_fv_over_domin.out.txt  test_other/height_ngp2_fv_over_domin.out.txt
echo height_ngp2_recess.out.txt && diff height_ngp2_recess.out.txt  test_other/height_ngp2_recess.out.txt
echo height_ngp2_fv_recess.out.txt && diff height_ngp2_fv_recess.out.txt  test_other/height_ngp2_fv_recess.out.txt
echo height_ngp2_2df.out.txt && diff height_ngp2_2df.out.txt  test_other/height_ngp2_2df.out.txt
echo height_ngp2_fv_2df.out.txt && diff height_ngp2_fv_2df.out.txt  test_other/height_ngp2_fv_2df.out.txt
echo height_ngp2_allcov_add.out.txt && diff height_ngp2_allcov_add.out.txt  test_other/height_ngp2_allcov_add.out.txt
echo height_ngp2_allcov_fv_add.out.txt && diff height_ngp2_allcov_fv_add.out.txt  test_other/height_ngp2_allcov_fv_add.out.txt
echo height_ngp2_allcov_domin.out.txt && diff height_ngp2_allcov_domin.out.txt  test_other/height_ngp2_allcov_domin.out.txt
echo height_ngp2_allcov_fv_domin.out.txt && diff height_ngp2_allcov_fv_domin.out.txt  test_other/height_ngp2_allcov_fv_domin.out.txt
echo height_ngp2_allcov_over_domin.out.txt && diff height_ngp2_allcov_over_domin.out.txt  test_other/height_ngp2_allcov_over_domin.out.txt
echo height_ngp2_allcov_fv_over_domin.out.txt && diff height_ngp2_allcov_fv_over_domin.out.txt  test_other/height_ngp2_allcov_fv_over_domin.out.txt
echo height_ngp2_allcov_recess.out.txt && diff height_ngp2_allcov_recess.out.txt  test_other/height_ngp2_allcov_recess.out.txt
echo height_ngp2_allcov_fv_recess.out.txt && diff height_ngp2_allcov_fv_recess.out.txt  test_other/height_ngp2_allcov_fv_recess.out.txt
echo height_ngp2_allcov_2df.out.txt && diff height_ngp2_allcov_2df.out.txt  test_other/height_ngp2_allcov_2df.out.txt
echo height_ngp2_allcov_fv_2df.out.txt && diff height_ngp2_allcov_fv_2df.out.txt  test_other/height_ngp2_allcov_fv_2df.out.txt
echo height_ngp2_int1_add.out.txt && diff height_ngp2_int1_add.out.txt  test_other/height_ngp2_int1_add.out.txt
echo height_ngp2_int1_fv_add.out.txt && diff height_ngp2_int1_fv_add.out.txt  test_other/height_ngp2_int1_fv_add.out.txt
echo height_ngp2_int1_domin.out.txt && diff height_ngp2_int1_domin.out.txt  test_other/height_ngp2_int1_domin.out.txt
echo height_ngp2_int1_fv_domin.out.txt && diff height_ngp2_int1_fv_domin.out.txt  test_other/height_ngp2_int1_fv_domin.out.txt
echo height_ngp2_int1_over_domin.out.txt && diff height_ngp2_int1_over_domin.out.txt  test_other/height_ngp2_int1_over_domin.out.txt
echo height_ngp2_int1_fv_over_domin.out.txt && diff height_ngp2_int1_fv_over_domin.out.txt  test_other/height_ngp2_int1_fv_over_domin.out.txt
echo height_ngp2_int1_recess.out.txt && diff height_ngp2_int1_recess.out.txt  test_other/height_ngp2_int1_recess.out.txt
echo height_ngp2_int1_fv_recess.out.txt && diff height_ngp2_int1_fv_recess.out.txt  test_other/height_ngp2_int1_fv_recess.out.txt
echo height_ngp2_int1_2df.out.txt && diff height_ngp2_int1_2df.out.txt  test_other/height_ngp2_int1_2df.out.txt
echo height_ngp2_int1_fv_2df.out.txt && diff height_ngp2_int1_fv_2df.out.txt  test_other/height_ngp2_int1_fv_2df.out.txt
echo height_ngp2_robust_add.out.txt && diff height_ngp2_robust_add.out.txt  test_other/height_ngp2_robust_add.out.txt
echo height_ngp2_robust_fv_add.out.txt && diff height_ngp2_robust_fv_add.out.txt  test_other/height_ngp2_robust_fv_add.out.txt
echo height_ngp2_robust_domin.out.txt && diff height_ngp2_robust_domin.out.txt  test_other/height_ngp2_robust_domin.out.txt
echo height_ngp2_robust_fv_domin.out.txt && diff height_ngp2_robust_fv_domin.out.txt  test_other/height_ngp2_robust_fv_domin.out.txt
echo height_ngp2_robust_over_domin.out.txt && diff height_ngp2_robust_over_domin.out.txt  test_other/height_ngp2_robust_over_domin.out.txt
echo height_ngp2_robust_fv_over_domin.out.txt && diff height_ngp2_robust_fv_over_domin.out.txt  test_other/height_ngp2_robust_fv_over_domin.out.txt
echo height_ngp2_robust_recess.out.txt && diff height_ngp2_robust_recess.out.txt  test_other/height_ngp2_robust_recess.out.txt
echo height_ngp2_robust_fv_recess.out.txt && diff height_ngp2_robust_fv_recess.out.txt  test_other/height_ngp2_robust_fv_recess.out.txt
echo height_ngp2_robust_2df.out.txt && diff height_ngp2_robust_2df.out.txt  test_other/height_ngp2_robust_2df.out.txt
echo height_ngp2_robust_fv_2df.out.txt && diff height_ngp2_robust_fv_2df.out.txt  test_other/height_ngp2_robust_fv_2df.out.txt
echo height_ngp2_robust_int1_add.out.txt && diff height_ngp2_robust_int1_add.out.txt  test_other/height_ngp2_robust_int1_add.out.txt
echo height_ngp2_robust_int1_fv_add.out.txt && diff height_ngp2_robust_int1_fv_add.out.txt  test_other/height_ngp2_robust_int1_fv_add.out.txt
echo height_ngp2_robust_int1_domin.out.txt && diff height_ngp2_robust_int1_domin.out.txt  test_other/height_ngp2_robust_int1_domin.out.txt
echo height_ngp2_robust_int1_fv_domin.out.txt && diff height_ngp2_robust_int1_fv_domin.out.txt  test_other/height_ngp2_robust_int1_fv_domin.out.txt
echo height_ngp2_robust_int1_over_domin.out.txt && diff height_ngp2_robust_int1_over_domin.out.txt  test_other/height_ngp2_robust_int1_over_domin.out.txt
echo height_ngp2_robust_int1_fv_over_domin.out.txt && diff height_ngp2_robust_int1_fv_over_domin.out.txt  test_other/height_ngp2_robust_int1_fv_over_domin.out.txt
echo height_ngp2_robust_int1_recess.out.txt && diff height_ngp2_robust_int1_recess.out.txt  test_other/height_ngp2_robust_int1_recess.out.txt
echo height_ngp2_robust_int1_fv_recess.out.txt && diff height_ngp2_robust_int1_fv_recess.out.txt  test_other/height_ngp2_robust_int1_fv_recess.out.txt
echo height_ngp2_robust_int1_2df.out.txt && diff height_ngp2_robust_int1_2df.out.txt  test_other/height_ngp2_robust_int1_2df.out.txt
echo height_ngp2_robust_int1_fv_2df.out.txt && diff height_ngp2_robust_int1_fv_2df.out.txt  test_other/height_ngp2_robust_int1_fv_2df.out.txt
echo mmscore_add.out.txt && diff mmscore_add.out.txt  test_other/mmscore_add.out.txt
echo mmscore_fv_add.out.txt && diff mmscore_fv_add.out.txt test_other/mmscore_fv_add.out.txt
echo mmscore_prob_add.out.txt && diff mmscore_prob_add.out.txt test_other/mmscore_prob_add.out.txt 
echo mmscore_prob_fv_add.out.txt && diff mmscore_prob_fv_add.out.txt test_other/mmscore_prob_fv_add.out.txt
